# This is a basic workflow to help you get started with Actions
name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ matthias-action, master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    # Create a folder for the Doxygen html output
    - run:  mkdir build
    - run:  mkdir build/docs
    # - run:  ls -lisa              # just for debugging
    # - run:  ls -lisa build/docs   # just for debugging
      
        
    # Create the doxygen Documentation
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.9.4
      with:
        # Path to Doxyfile
        doxyfile-path: "./DoxyConf"
        # Working directory where doxygen runs
        working-directory: "./Documents/src/" 
        
    # Check if the output is there 
    - run:  ls -lisa build/docs
    - run:  ls -lisa build/docs/html

    # push the generated output to gh-pages branch
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      # Only attempt to deploy from the master branch
      if: github.ref == 'refs/heads/master'
      # To avoid nuisance job errors, this step is allowed to fail on forks or non-master branches without signaling workflow failure
      continue-on-error: ${{ github.repository != 'ttlappalainen/NMEA2000' || github.ref != 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/docs/html
